### ISSUE TITLE
How does it compare to an asm.js version of md5?

### ISSUE THREAD

**Issue by GirkovArpa** [briantbutton/md5-wasm#1]
I recently posted [this](https://old.reddit.com/r/WebAssembly/comments/g8oxaa/wasm_simd_is_almost_500x_as_fast_as_js_at/) dot-product benchmark showing Wasm to be 500x faster than JS.  It's very variable though; sometimes it's only 200x faster, sometimes it's almost 1000x faster.

Then someone recommended an asm.js dot-product script (well, it was compiled by Cheerp to something close to asm.js anyway) and the Wasm was less than 10x faster.

So I wonder if the 30x benchmark would stand against an asm.js version of md5.

**Comment by briantbutton** [comment]
GirkovArpa, I have never had much luck projecting how a benchmark will turn out but, with that caveat, I would assume they would have comparable performance.  No reason to expect otherwise.

My basic protocol is to start by squeezing every ounce of performance out of the JavaScript by using typed arrays and lots of small optimizations.  Sometimes that gives me a lot; JavaScript compilers are pretty darn smart.

I did that here.  MD5-WASM includes a pure JavaScript path.  Both paths are used in all calculations.  It does "bite-sized" chunks in WASM until the remaining data drops below bite-sized and then it finishes off with JavaScript.

I found a WASM overhead for instantiation and going in/out.  So, for small files, MD5-WASM never instantiates WASM and just does JavaScript.
